title: Title goes here
description: Description goes here.
show_downloads: true
theme: jekyll-theme-midnight

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
  plugins:
  - jekyll-paginate
  - jekyll-sitemap
